
jobs:

  - job: MacOSX
    pool:
      vmImage: macOS 10.13
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: 3.7
    - bash: pip install vispy PyQt5
    - bash: python test.py

  - job: Windows
    pool:
      vmImage: vs2017-win2016
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: 3.7
    - bash: pip install vispy PyQt5
    - bash: python test.py

  - job: Linux
    pool:
      vmImage: Ubuntu 16.04
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: 3.7
    - bash: pip install vispy PyQt5
    - bash: python test.py